### PR TITLE
Add new tocall

### PR DESCRIPTION
**Pull request by lwkoon**
Add new tocall deviceid

### CODE REVIEW

**Comment by lwkoon** [comment]
re-validated

**Review by hessu — CHANGES_REQUESTED** [review]
Hello,

This PR still includes the generated files, please only include changes in tocalls.yaml as requested previously.

LoRa devices have been recently added in the APL* prefix for easier filtering. How about if I make the allocation for you for APLDG? and APLDH? with a PR of my own?

**Comment by lwkoon** [comment]
Hi,
Do i need to re-create the PR?

Yes, you may amend APLDG? and APLDH? with  your own.

Thanks
Eddie 9W2LWK

**Comment by hessu** [comment]
Hi,

Thanks. I have added APLDG? and APLDH? in #143 so you can use them with an additional alphanumeric character for versioning or further variants, APLDG0 APLDG1 APLDGA APLDGZ, etc.

73!

**Comment by lwkoon** [comment]
Thanks

**Pull request closed without merging**
